source 'http://rubygems.org'

gem 'jekyll'
gem 'haml'
gem 'rake'
gem 'RedCloth'
gem 'rdiscount'
gem 'sass'
gem 'coffee-script'
gem 'foreman'
gem 'rb-fsevent'
gem 'guard'
gem 'guard-livereload'
gem 'guard-jekyll'