// Generated by CoffeeScript 1.4.0

jQuery(function() {
  var mobile;
  mobile = function(width) {
    if (width < 768) {
      return $("section.info").addClass("one");
    } else {
      return $("section.info").removeClass("one");
    }
  };
  $(window).resize(function() {
    return mobile($(this).width());
  });
  $(window).resize();
  $("[data-title]").tooltip();
  if ($("ul.posts").length > 0 && window.location.origin.indexOf("localhost") < 0) {
    $.each($("ul.posts li a"), function(index, a) {
      var appd, facebook_query, t, twitter_query, url;
      url = "http://muan.co" + $(a).attr("href");
      twitter_query = 'http://urls.api.twitter.com/1/urls/count.json?callback=?&url=' + url;
      facebook_query = 'http://graph.facebook.com/?id=' + url;
      t = a;
      $.getJSON(twitter_query, function(res) {
        t.t_count = res.count || 0;
        if (typeof t.f_count !== "undefined") {
          return appd();
        }
      });
      $.getJSON(facebook_query, function(res) {
        t.f_count = res.shares || 0;
        if (typeof t.t_count !== "undefined") {
          return appd();
        }
      });
      return appd = function() {
        return $(a).find(".shares").html("⚑ " + (t.t_count + t.f_count));
      };
    });
  }
  $.each($("pre"), function(index, code) {
    return new CodeMirror(function(node) {
      if (code instanceof jQuery) {
        code = code.get(0);
      }
      return code.parentNode.replaceChild(node, code);
    }, {
      value: $.trim(code.textContent.split("||")[1]),
      readOnly: true,
      mode: $.trim(code.textContent.split("||")[0]),
      theme: "monokai",
      lineNumbers: $.trim(code.textContent.split("||")[1]).match("\\n"),
      matchBrackets: true
    });
  });
  $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
  $.each($("a[id]"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      return _gaq.push(["_trackEvent", "Clicks", "clicked", e.target.id]);
    });
  });
  return $.each($("a:not([id])"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      console.log(e.currentTarget.innerText);
      return _gaq.push(["_trackEvent", "Visits", "clicked on" + e.currentTarget.innerText, e.currentTarget.href]);
    });
  });
});
