// Generated by CoffeeScript 1.4.0

$.fn.tooltip = function() {
  var content, left, tooltip, top;
  content = $(this).attr("title");
  tooltip = $("<div class=\"tooltip\"><div class=\"arrow\"></div>" + content + "</div>");
  $(this).after(tooltip);
  top = $(this).position().top;
  left = $(this).position().left;
  tooltip.css({
    "top": top
  }).css({
    "left": left
  });
  return $(this).hover(function() {
    return tooltip.show();
  }, function() {
    return tooltip.hide();
  });
};
